// This file was generated by wix-one-app-engine on Wed Sep 30 2020
// You can extend it if you want, but leave the defaults to be required from the engine config

module.exports = {
  ...require('./node_modules/wix-one-app-engine/tools/engine_cli/etc/metro.config')
};
