// This file is auto-generated by wix-one-app-engine

export default {
  'wix-one-app-platform': () => require('wix-one-app-platform').default,
  'ofer_intro': () => require('ofer_intro').default,
  'ofer_intro-demo': () => require('ofer_intro-demo').default
}
;