// This file is auto-generated by wix-one-app-engine

export default {
  'wix-one-app-platform': () => require('./module_js/wix-one-app-platform.json'),
  'ofer_intro': () => require('./module_js/ofer_intro.json'),
  'ofer_intro-demo': () => require('./module_js/ofer_intro-demo.json')
};