require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ofer_intro' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'ReactNativeUiLib', :path => '../node_modules/react-native-ui-lib/lib'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'ofer_introTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ofer_intro-tvOS' do
  # Pods for ofer_intro-tvOS

  target 'ofer_intro-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
